server:
  port: ${SERVER_PORT:9999}

grpc:
  port: ${GRPC_PORT:50052}

spring:
  application:
    name: resource-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: true
        highlight_sql: true
